database:
    name      : example
    type      : postgresql
    host      : "127.0.0.1"
    port      : 5432
    user      : christoph
    password  : pwd1234
tables:
    - film
    - actor
    - address
    - inventory
    - language
    - staff